name: flutterflow_cli
description: >-
  Command-line client for FlutterFlow. Export code from FlutterFlow projects.
version: 0.0.9
homepage: https://github.com/FlutterFlow/flutterflow-cli
issue_tracker: https://github.com/flutterflow/flutterflow-issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  archive: ^3.3.5
  args: ^2.3.0
  http: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0

executables:
  flutterflow: flutterflow_cli
